export default {
  openMenuBtn: document.querySelector('.js-open-menu '),
  closeMenuBtn: document.querySelector('.js-close-menu'),
  mobileMenu: document.querySelector('.js-menu-container'),
  mobileBackdrop: document.querySelector('.js-mobile-backdrop'),
  burgerIcon: document.querySelector('.burger-icon'),
  closeIcon: document.querySelector('.close-icon'),
  toHomeBtn: document.querySelectorAll('.js-nav-home'),
  toAboutBtn: document.querySelectorAll('.js-nav-about'),
  toGalleryBtn: document.querySelectorAll('.js-nav-gallery'),
  allTranslateEls: document.querySelectorAll('.i18n'),
  allTranslateBtns: document.querySelectorAll('.js-lang-btn'),
  aboutGalleryList: document.querySelector('.about-gallery-list'),
  galleryList: document.querySelector('.gallery-list'),
  html: document.querySelector('html'),
  metaDescription: document.querySelector('meta[name="description"]'),
  navLinks: document.querySelectorAll('.js-nav-link'),
};
